version: '3'

networks:
  logging:

services:
  loki:
    image: grafana/loki:${LOKI_TAG}
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - logging

  promtail:
    image: grafana/promtail:${PROMPTAIL_TAG}
    expose:
      - 9080
    ports:
      - "9080:9080"
    volumes:
      - /home/ubuntu/var/lib/docker/containers:/var/lib/docker/containers:ro
      - /home/ubuntu/devops/monitoring/promtail.yml:/etc/promtail/promtail.yml
    command: -config.file=/etc/promtail/promtail.yml
    networks:
      - logging

  grafana:
    image: grafana/grafana:${GRAFANA_TAG}
    ports:
      - "3000:3000"
    networks:
      - logging

