version: '2.4'

x-logging:
  &default-logging
  options:
    tag: "{{ .ImageName }}|{{ .Name }}"
    max-size: '100m'
    max-file: '3'
  driver: json-file

x-custom:
  &network-logging
  logging: *default-logging
  networks:
    - logging

networks:
  logging:

services:
  app:
    image: nufusrufus/devops:${APP_TAG}
    container_name: monitoring-app
    ports:
      - "8000:8000"
    <<: *network-logging
      

  loki:
    image: grafana/loki:${LOKI_TAG}
    container_name: monitoring-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    <<: *network-logging

  promtail:
    image: grafana/promtail:${PROMTAIL_TAG}
    container_name: monitoring-promtail
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail.yml:/etc/promtail/promtail.yml
    command: -config.file=/etc/promtail/promtail.yml
    <<: *network-logging

  grafana:
    image: grafana/grafana:${GRAFANA_TAG}
    container_name: monitoring-grafana
    ports:
      - "3000:3000"
    <<: *network-logging
