registry: nufusrufus
image: devops
image_tag: ci-54c99a75a2169cb0ac19dad25d0b920639454de1

app_base_path: /opt/app_python
app_data_path: "{{ app_base_path }}/data"
app_compose_path: "{{ app_base_path }}/docker-compose.yml"

app_http_port: "8000"
app_ssh_port: "22"