# Default values for my-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: nufusrufus/devops
  pullPolicy: IfNotPresent
  tag: ci-d6a418a2c30a0faf74539a1baf741b8c5f373c2d
  port: 8000

volumes:
  visits: home/app/files
  wget: home/app/wget

secrets:
  name: my-secret
  username: my-app # Change to your secret username

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  name: app-service
  type: LoadBalancer
  port: 8000

resources:
  requests:
    cpu: ".2"
    memory: "100Mi"
  limits:
    cpu: ".5"
    memory: "256Mi"

statefulSet:
  podManagementPolicy: "Parallel"
  volumeClaimTemplates:
    spec: 
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 256M

configMap:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}
