# Default values for my-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: nufusrufus/devops
  pullPolicy: IfNotPresent
  tag: ci-352d1baeee4e15517cc2d2eb43b129f64b6dc3b7
  port: 8000
  workDir: home/app/files

secrets:
  name: my-secret
  username: my-app # Change to your secret username

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 8000

resources:
  requests:
    cpu: ".2"
    memory: "100Mi"
  limits:
    cpu: ".5"
    memory: "256Mi"

nodeSelector: {}

tolerations: []

affinity: {}
