# Default values for my-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: nufusrufus/devops
  pullPolicy: IfNotPresent
  tag: ci-ef46b23648566e3af3d785e22b2c2d85e1ece5eb
  port: 8000

secrets:
  name: my-secret
  username: my-app # Change to your secret username

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 8000

resources:
  limits:
    cpu: ".3"
    memory: "128Mi"

nodeSelector: {}

tolerations: []

affinity: {}
