# Default values for my-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: nufusrufus/devops
  pullPolicy: IfNotPresent
  tag: "latest"
  port: 8000

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 8000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
