# Reference: https://github.com/storageos/helm-chart/blob/master/templates/secrets.yaml
# This secret is used to set the initial credentials of the node container.

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    app: {{ include "my-app.fullname" . }}
    chart: {{ include "my-app.chart" . }}
type: Opaque
data:
  username: {{ default "" .Values.secrets.username | b64enc | quote }}
