name: Linting and Testing

on: [ pull_request ]

jobs:
  linting_and_testing:
    runs-on: ubuntu-latest
    env:
      working_dir: app_python
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: pip install -r ${{ env.working_dir }}/requirements.txt
      - name: Lint with flake8
        run: flake8 app_python
        continue-on-error: true
      - name: Test with pytest
        run: pytest ${{ env.working_dir }}/tests --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml
